# Handles escalation logic, confidence reporting, and medical disclaimers.

from datetime import datetime

ESC_EN = {
    "urgent":   "You have {count} result(s) significantly outside the normal range. This system cannot diagnose medical conditions, but results like these typically require timely medical evaluation. Please contact your doctor within the next few days.",
    "schedule": "You have {count} result(s) moderately outside the normal range. These should be reviewed with your doctor at your next appointment.",
    "monitor":  "You have {count} result(s) mildly outside the normal range. These are worth noting and discussing at your next routine visit.",
}

ESC_AR = {
    "urgent":   "عندك {count_ar} خارجة عن المعدل الطبيعي. النظام لا يمكنه تشخيص الحالات الطبية، لكن مثل هذه النتائج تستلزم الرعاية الطبية العاجلة. يرجى التواصل مع طبيبك خلال الأيام القادمة.",
    "schedule": "عندك {count_ar} خارجة عن المعدل الطبيعي بشكل ملحوظ. ينبغي مراجعة هذه النتائج مع طبيبك في موعدك القادم.",
    "monitor":  "عندك {count_ar} خارجة قليلاً عن المعدل الطبيعي. ناقشها مع طبيبك في زيارتك الروتينية القادمة.",
}

EMERGENCY_EN = """### Seek Emergency Care Immediately If You Experience:
- Severe chest pain or pressure
- Difficulty breathing or shortness of breath
- Sudden severe headache
- Loss of consciousness or fainting
- Sudden weakness or numbness in face, arm or leg
- Severe abdominal pain

Do not rely on this report to determine if you have an emergency. Call emergency services (911 / 997 in Saudi Arabia) if in doubt."""

EMERGENCY_AR = """### اطلب الرعاية الطارئة فوراً إذا عانيت من:
- ألم شديد في الصدر أو ضغط
- صعوبة في التنفس أو ضيق في التنفس
- صداع حاد مفاجئ
- فقدان الوعي أو الإغماء
- ضعف أو خدر مفاجئ في الوجه أو الذراع أو الساق
- ألم شديد في البطن

لا تعتمد على هذا التقرير لتحديد ما إذا كنت في حالة طوارئ. اتصل بخدمات الطوارئ (911 / 997 في المملكة العربية السعودية) عند الشك."""

DISCLAIMER_EN = """---
## Important Medical Disclaimer

This report is generated by an AI system for educational and informational purposes only.

- This system is not a licensed medical professional and cannot diagnose, treat, or prescribe.
- Reference ranges shown are general population standards and may not apply to your individual circumstances (age, sex, medications, ethnicity, pregnancy, etc.).
- Lab values must always be interpreted in the full context of your medical history, symptoms, and clinical examination by a qualified physician.
- Do not make medical decisions based solely on this AI-generated explanation.
- Results may be inaccurate if the original PDF format differs significantly from the expected format.

Always consult a qualified healthcare provider for medical advice.

*Report generated: {timestamp}*"""

DISCLAIMER_AR = """---
## إخلاء المسؤولية الطبية

هذا التقرير منشأ بواسطة نظام ذكاء اصطناعي لأغراض تعليمية ومعلوماتية فقط.

- هذا النظام ليس متخصصاً طبياً مرخصاً ولا يستطيع تشخيص أو علاج أو وصف الأدوية.
- المعدلات المرجعية المعروضة هي معايير عامة للسكان وقد لا تنطبق على ظروفك الفردية (العمر، والجنس، والأدوية، والعرق، والحمل، إلخ).
- تذكر دائماً عليك أن تفسر قيم المختبر في سياق كامل لتاريخك الطبي، وأعراضك، والفحص السريري الذي يجريه الطبيب المؤهل.
- لا تتخذ قرارات طبية بناءً على هذا التفسير الذي أنشأه الذكاء الاصطناعي فقط.
- قد تكون النتائج غير دقيقة إذا اختلف تنسيق ملف PDF الأصلي بشكل كبير عن التنسيق المتوقع.

دائماً استشر مقدم رعاية صحية مؤهلاً للحصول على مشورة طبية.

*تاريخ إنشاء التقرير: {timestamp}*"""


def _confidence_report(tests):
    if not tests:
        return {"mean": 0, "min": 0, "max": 0, "total_tests": 0, "low_conf_count": 0,
                "low_conf_tests": [], "interpretation": "No tests analyzed."}
    confs = [t["confidence"] for t in tests]
    low = [t for t in tests if t["confidence"] < 0.80]
    return {
        "mean": round(sum(confs) / len(confs), 3),
        "min": round(min(confs), 3),
        "max": round(max(confs), 3),
        "total_tests": len(tests),
        "low_conf_count": len(low),
        "low_conf_tests": [t["test_name"] for t in low],
        "interpretation": (
            "High confidence — all values confirmed by both PDF flags and computed range comparison."
            if all(c >= 0.90 for c in confs)
            else "Moderate confidence — some values could not be fully verified. Review original PDF."
        ),
    }


def generate_escalation(explained: dict) -> dict:
    tests = explained["tests"]
    significant = sum(1 for t in tests if t.get("severity") == "significant" and t["flag"] != "NORMAL")
    moderate    = sum(1 for t in tests if t.get("severity") == "moderate"    and t["flag"] != "NORMAL")
    mild        = sum(1 for t in tests if t.get("severity") == "mild"        and t["flag"] != "NORMAL")

    if significant > 0:   level, count = "urgent",   significant
    elif moderate > 0:    level, count = "schedule", moderate
    elif mild > 0:        level, count = "monitor",  mild
    else:                 level, count = "all_normal", 0

    esc_en = ESC_EN.get(level, "").format(count=count)
    # Arabic proper count
    if count == 1:   count_ar = "نتيجة واحدة"
    elif count == 2: count_ar = "نتيجتين"
    elif count <= 10: count_ar = f"{count} نتائج"
    else:            count_ar = f"{count} نتيجة"
    esc_ar = ESC_AR.get(level, "").format(count_ar=count_ar)

    followup_en_lines, followup_ar_lines = [], []
    for t in tests:
        if t.get("needs_followup"):
            name = t.get("full_name") or t["test_name"].split("—")[0].strip()
            followup_en_lines.append(f"- **{name}**: {t['result_raw']} {t['unit']} (normal: {t['ref_raw']}) — {t.get('concern','consult physician')}")
            followup_ar_lines.append(f"- **{name}**: {t['result_raw']} {t['unit']} (المعدل: {t['ref_raw']})")

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    return {
        **explained,
        "escalation_level": level,
        "escalation_en": esc_en,
        "escalation_ar": esc_ar,
        "emergency_en": EMERGENCY_EN,
        "emergency_ar": EMERGENCY_AR,
        "followup_en": ("### When You See Your Doctor, Discuss These Results:\n" + "\n".join(followup_en_lines)) if followup_en_lines else "",
        "followup_ar": ("### عند زيارة طبيبك، ناقش هذه النتائج:\n" + "\n".join(followup_ar_lines)) if followup_ar_lines else "",
        "disclaimer_en": DISCLAIMER_EN.format(timestamp=timestamp),
        "disclaimer_ar": DISCLAIMER_AR.format(timestamp=timestamp),
        "confidence_report": _confidence_report(tests),
        "severity_counts": {"significant": significant, "moderate": moderate, "mild": mild},
        "report_timestamp": timestamp,
    }

if __name__ == "__main__":
    import sys
    sys.path.insert(0, "src")
    from step1_extract import extract_from_pdf
    from step2_compare import analyze_tests
    from step3_explain import generate_explanations
    path = sys.argv[1] if len(sys.argv) > 1 else "sample_data/sample_blood_test.pdf"
    final = generate_escalation(generate_explanations(analyze_tests(extract_from_pdf(path))))
    print(f"Level: {final['escalation_level']}")
    print(final['escalation_ar'])
